

FROM --platform=$BUILDPLATFORM ubuntu:latest

ARG WE_VERSION=14.3
ENV WE_VERSION=$WE_VERSION


RUN     cd \
    &&  apt-get update && apt-get upgrade -y && apt-get install -y build-essential ca-certificates sudo wget libegl-dev \
    &&  useradd -m -s /bin/bash -p wolframengine wolframengine \
    &&  wget --no-verbose https://archive.raspberrypi.org/debian/pool/main/w/wolfram-engine/wolfram-engine_14.3.0+202510021899_arm64.deb \
    &&  yes | apt-get install -y ./wolfram-engine_14.3.0+202510021899_arm64.deb \
    &&  rm ./wolfram-engine_14.3.0+202510021899_arm64.deb

WORKDIR /home/wolframengine
USER wolframengine

RUN     mkdir -p dist \
    &&  cp -r /opt/Wolfram/WolframEngine/${WE_VERSION}/SystemFiles/Links/WSTP/DeveloperKit/Linux-ARM64/CompilerAdditions/wstp.h dist/ \
    &&  cp -r /opt/Wolfram/WolframEngine/${WE_VERSION}/SystemFiles/Libraries/Linux-ARM64/* dist/
